spring.application.name=appServifarmaB

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Logging Configuration
logging.level.com.example.proyecto.app.security=DEBUG
logging.level.org.springframework.security=INFO

# JSON Configuration (RENIEC)
jsonpe.api-key=${JSONPE_API_KEY}

# Server configuration
server.port=8080
spring.main.allow-bean-definition-overriding=true

# CORS Configuration
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
app.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
app.cors.allowed-headers=*
app.cors.allow-credentials=true

# Static Resources (para uploads)
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.web.resources.add-mappings=true
spring.main.allow-circular-references=true